---
title: "Combine and Classify Fire Severity"
author: "Shive Lab (B. Baker)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(terra)
library(here)

```

#Combine Rasters from GEE

```{r}
# #Load seperate rdmbr rasters -- maybe automate later
# case <- rast(here("data/spatial_data/needSeverity_state-of-segi/CASE_1987_rdnbr.tif"))
# 
# circle <- rast(here("data/spatial_data/needSeverity_state-of-segi/CIRCLE_2002_rdnbr.tif"))
# 
# deer <- rast(here("data/spatial_data/needSeverity_state-of-segi/DEER-CREE_1991_rdnbr.tif"))
# 
# panther <- rast(here("data/spatial_data/needSeverity_state-of-segi/PANTHER_1994_rdnbr.tif"))
# 
# tharp <- rast(here("data/spatial_data/needSeverity_state-of-segi/THARPS_2018_rdnbr.tif"))

```

```{r}
# ## make spatial raster collection
# s <- sprc(case, circle, deer, panther, tharp)
# 
# ## merge rasters
# severity_rdnbr <- merge(s)
# 
# #output new combined raster
# writeRaster(severity_rdnbr, here("data/spatial_data/needSeverity_rdnbr.tif"))

severity_rdnbr <- rast(here("data/spatial_data/needSeverity_rdnbr.tif"))

```

```{r}
#view to visualize
plot(severity_rdnbr)

```

#Classify to Basal Area % Change Severity

Breaks follow the 7 class % change in Basal Area severity used in the R5:Veg Burn Severity BA.

* 0% Change (0.00001)
* 0% < Change < 10% (10)
* 10% <= Change < 25% (25)
* 25% <= Change < 50% (50)
* 50% <= Change < 75% (75)
* 75% <= Change < 90% (90)
* Change > 90%

To classify the rdnbr raster using these breaks, we will need to determine the corresponding rdnbr value for the BA perc. This is done using the equation in miller 2009, Table 3 (!https://www.fs.usda.gov/psw/publications/knapp/psw_2009_knapp(miller)001.pdf).

RdNBR = a + b ⁎ ASIN(SQRT(PctBA / 100)) where a = 166.5, b = 389.0

```{r}
#define breaks
category_names <- c("0% Change", "0% < Change < 10%", "10% <= Change < 25%", "25% <= Change < 50%","50% <= Change < 75%", "75% <= Change < 90%", "Change > 90%")

breaks <- tibble(
  ba_from = c(0, 0, 10, 25, 50, 75, 90), #lefthand breaks BA
  ba_to = c(0, 10, 25, 50, 75, 90, 100), #righthand breaks in BA
  rdnbr_from = 166.5 + 389 * asin(sqrt(ba_from/100)), #converted to rdnbr
  rdnbr_to = 166.5 + 389 * asin(sqrt(ba_to/100)), #converted to rdnbr
  becomes =  c(1, 2, 3, 4, 5, 6, 7)) %>% #name of categories
  select(!contains("ba")) #removes unneeded columns
  
breaks[1,1] = minmax(severity_rdnbr)[1] #make lowest category include minimum in raster
breaks[7,2] = minmax(severity_rdnbr)[2] #and highest be max in raster

```



```{r}
#classify raster

severity_ba <- classify(severity_rdnbr, breaks, 
                        right = F, # include "from" value in category
                        include.lowest = T) %>% #include max value 
  as.factor() #make factor

x <- levels(severity_ba)[[1]] %>% #pull levels of raster
  rename(ba_category = rdnbr) # rename level

x$class <- category_names #add categories as a level

levels(severity_ba) <- x #save new levels back

#writeRaster(severity_ba, here("data/spatial_data/needSeverity_baClass7.tif"))

```

