---
title: "Regen Failure"
author: "Shive Lab (B. Baker)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = F, warning = F, error = F)

library(here)
library(tidyverse)
library(sf)
library(terra)

```

This document holds the analysis for regeneration failure areas.

```{r import_data}
#BA 7-class fires that have had high sev and are in groves 1984-2024 
sev_class7 <- st_read(here("data/spatial_data/outputs/ba_class7_poly/ba_class7_poly.shp"))

#polygons of SEGI groves, "skinny"
groves <- st_read(here("data/spatial_data/inputs/forest/2023_GS_Groves_OTI_public.gdb"), layer = "OGS_Groves_2023_97_public") %>%
  clean_names() %>%
  st_transform(crs(sev_ba_segi)) %>% #uniform crs
  st_cast("MULTIPOLYGON") 

```



```{r}
#grove filtered 7-class
#BA 7-class fires that have had high sev and are in groves 1984-2024 
sev_class7 <- st_read(here("data/spatial_data/outputs/ba_highsev_7/ba_highsev_7.shp")) %>% 
  st_transform(crs(cbi2017))

ba_class7_segi <- st_intersection(groves, sev_class7)

ba_class7_segi <- ba_class7_segi %>% 
  rename("grov_nm" = "grove_name",
         "fire_yr" = "year") %>% 
  select(grov_nm, id, burnsev, fire_yr) 

ba_class7_segi$area_ha <- as.numeric(st_area(ba_class7_segi))*0.0001 

#dir.create(here("data/spatial_data/outputs/ba_class7_poly"))
st_write(ba_class7_segi, here("data/spatial_data/outputs/ba_class7_poly/ba_class7_poly.shp"), append = F)

```

We will consider areas that fall into the highest burn severity category as those where regeneration failure is likely. The layer I am starting from contains rdnbr for fires from 1984-2023 that both burned at high severity and burned sequoia groves.

```{r sev_polygons}

high_sev <- 
  


```




