---
title: "resistance-assessment"
author: "Shive Lab (B. Baker)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(terra)
library(sf)
library(here)
library(janitor)

```

-input treatment data
-"union" to create independent treatment+disturbance history polygons



#Input and clean treatment data


```{r input_data}

#fire history in CBI
fire <- st_read(here("data/spatial_data/outputs/cbi_all/cbi_all.shp"))
 

#full, cleaned treatment layer (will this be the case?)
treatment <- st_read(here("data/spatial_data/inputs/treatment/NPS_Combined_TrtFile_1966_2023_repaired/NPS_Combined_TrtFile_1966_2023_repaired.shp")) %>% 
  st_transform(crs(fire))

#skinny jeans groves, exported to shp from gdb in arc bc polys were weird
groves <- st_read(here("data/spatial_data/inputs/forest/all_groves_REexported.shp")) %>%
  st_transform(crs(fire)) #uniform crs

```

```{r full_trt_lyr}

trt_clean <- treatment %>% 
  clean_names() %>%
  select(ucb_year, ucb_treat) %>%  # select only needed columns
  rename(dist_year = ucb_year,
         dist_type = ucb_treat)



```


```{r dist_lyr}

# create clean fire layer
fire_clean <- fire %>% 
  clean_names() %>% 
  mutate( #replace burnsev with class names, create cols to combine with trt
    dist_type = case_when(
      burnsev == 1 ~ "undetected_fire",
      burnsev == 2 ~ "lowsev_fire",
      burnsev == 3 ~ "modsev_fire",
      burnsev == 4 ~ "highsev_fire"),
    dist_year = as.numeric(fire_yr)
  ) %>% 
  select(dist_year, dist_type)#only needed columns
  
#combine to into all disturbance layer

disturb <- fire_clean %>% 
  bind_rows(trt_clean)

```


reminder: do both with buffer and without; need to decide if doing donut or all and subtracting after
```{r buffer}

#buffer groves by 75m
groves_buffered <- st_buffer(groves, dist = 75)

#reduce disturbance to within (buffered) groves
dist_groves <- st_intersection(disturb, groves_buffered) %>% 
  select(dist_year, dist_type) %>% 
  mutate(dist_id = 1:length(dist_year))

dist_groves_lookup <- dist_groves %>% 
  st_drop_geometry()

```

```{r dist_hist}

options(scipen = 999)

dist_hist <- st_intersection(dist_groves) %>% 
  mutate(resist_id = 1:length(origins)) %>% 
  select(resist_id, origins) %>% 
  st_collection_extract(type = c("POLYGON"), warn = FALSE) %>% #keep only polys
  #recombine multipolygons
  summarise(.by = c(resist_id, origins), geometry = st_combine(geometry)) %>% 
  mutate(area_ha = as.numeric(st_area(.))*0.0001) %>% 
  # remove areas less than 1 acre (likely "overlap" due to poorly mapped edges)
  filter(area_ha >= 0.04) 

#cannot plot with vectors
dist_plot <- dist_hist %>%
  select(-origins)

#st_write(dist_plot, here("data/spatial_data/debug/dist_lyr3_debug.shp"), append = F)

dist_hist_long <- dist_hist %>% 
  st_drop_geometry() %>%  # attributes only
  unnest(origins) %>%  # make long dataframe
  rename(dist_id = origins) %>% 
  left_join(dist_groves_lookup, by = join_by(dist_id)) %>% # connect with disturbance attributes
  select(-dist_id)

```


```{r}
dist_order <- dist_hist_long %>% 
  rename(
    current_dist_yr = dist_year,
    current_dist_type = dist_type
  ) %>% 
  group_by(resist_id) %>%
  # identify next treatment where relevant
  # note: use lead if year = character, lag if year = numeric
  mutate(
    current_dist_type = tolower(current_dist_type),
    next_dist_yr = lag(current_dist_yr, 1),
    next_dist_type = lag(current_dist_type, 1)) #%>%
  ungroup() #%>%
  #set definition of classes, including the exclusion of burn then thin
  mutate(burn_before_mech = 
           # will replace burnyear with current_disturb_year, and replace 
           # burnsev with current_disturb_type
         case_when(current_disturb_type %in% c("highsev_fire") & next_disturb_type %in% c("COMM_HAZ","MECH_UNDR","RX_PILE") ~TRUE,
                   TRUE~FALSE))

```




```{r}

# define resistance classes
polys_wide_sum <- polys_wide %>%
  group_by(polyID) %>%
  summarise(across(c(6:11), sum))
# View(polygons_dist_classes)
head(polys_wide_sum)
#   
#   
polygons_dist_classes =  polys_wide_sum %>%
  group_by(polyID) %>%
  summarise(resist_class =
      case_when(
      #High resistance
        # mod or low or rx + any mech
        # mod or low or rx + mod or low or rx
        (COMM_HAZ + MECH_UNDER + RX_PILE + MOD_SEV + LOW_SEV) >= 2 & (RX_PILE + MOD_SEV + LOW_SEV)>=1 & HIGH_SEV == 0 ~ 'High resistance',
      # #Mod resistance
        # mod or low or rx
        (RX_PILE + MOD_SEV + LOW_SEV) == 1 & (COMM_HAZ+MECH_UNDER) == 0 & HIGH_SEV == 0 ~ 'Moderate resistance',
      # #Low resistance
       # any mech
       (RX_PILE + MOD_SEV + LOW_SEV) == 0 & (COMM_HAZ+MECH_UNDER) >= 1 & HIGH_SEV == 0 ~ 'Low resistance',
      #Loss of mature forest
       # any high
       HIGH_SEV == 1 ~ 'Loss of mature forest',
      #Likely persistant type conversion
       # High-High
       HIGH_SEV > 1 ~ 'Likely persistent type conversion'))
polygons_dist_classes

poly_data = merge(polygons_dist_classes,polys_dist_order_screen,by="polyID",all=FALSE)
head(poly_data)

#don't need burn before mech here - if HS before mech, it will just show loss of forest
#if mod or low sev - we will assume it was clean up
#confirm with Charlotte but it looks like summary tables were calculated annually as appropriate
true = poly_data %>%
  filter(burn_before_mech == FALSE)
head(true)

sum(true$Hectares)

# View(poly_data)
poly_data_ac = poly_data %>%
  group_by(polyID,resist_class) %>%
  summarise(Hectares = mean(Hectares))
head(poly_data_ac)
```










