---
title: "Severity Estimations"
author: "Shive Lab (B. Baker)"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)      # sets directory and locates files
library(tidyverse) # data manipulation
library(sf)        # GIS (vector)
library(terra)     # GIS (raster)
library(readxl)    # read excel files directly
library(kableExtra)# make tables
library(janitor)   # clean data names
library(dygraphs)  # html visualizations (timeseries)
library(xts)       # convert data-frame > xts format (timeseries)
library(lubridate) # date manipulation
library(htmlwidgets)
library(harrypotter)
library(scales)
# library(LaCroixColoR)


```

## Load Data

To make severity estimates, I will use our complete CBI layer

```{r load}

#four-class CBI severity for all fires that intersect groves, not clipped to groves
cbi_all <- st_read(here("data/spatial_data/outputs/cbi_all/cbi_all.shp"))

cbi_all$area_ha_total <- as.numeric(st_area(cbi_all))*0.0001

#polygons of SEGI groves
groves <- st_read(here("data/spatial_data/inputs/forest/FINAL_SEGI_AnalysisArea_wOwnerships_GroveNames_noBuff/FINAL_SEGI_AnalysisArea_wOwnerships_GroveNames_noBuff.shp")) %>%
  clean_names() %>% 
  st_transform(crs(cbi_all)) %>%  #uniform crs
  st_make_valid()

cbi_all_24 <- cbi_all %>%
  filter(fire_yr == 2024) %>%
  st_union()

grove_area_2024 = groves %>%
    st_intersection(cbi_all_24) %>%
  st_cast("MULTIPOLYGON")
grove_area_2024$area_ha2 = st_area(grove_area_2024)*0.0001

grove_area_2024_sum = grove_area_2024  %>%
  st_drop_geometry() %>%
  group_by(grove_name) %>%
  summarise(area_ha = as.numeric(sum(area_ha2))) %>%
  filter(grove_name != "Garfield") %>%
  # mutate(grov_nm = grove_name) %>%
  mutate(year = 2024, fire_name = "Coffee Pot", id = "2024COFFEEPOT")
# %>%
#   select(-grove_name)

area_ha_2024 = sum(grove_area_2024$area_ha)

```

```{r}
#highsev grove area 2020 +2021 in SEKI

cbi_all_20_21 <- cbi_all %>%
  filter(fire_yr %in% c(2020, 2021),
         burnsev == 4) %>%
  st_union()

grove_area_20_21 = groves %>%
    st_intersection(cbi_all_20_21) %>%
  st_cast("MULTIPOLYGON")
grove_area_20_21$area_ha = st_area(grove_area_20_21)*0.0001

grove_area_20_21sum = grove_area_20_21  %>%
  st_drop_geometry() %>%
  group_by(unit_name) %>%
  summarise(totalarea_ha = as.numeric(sum(area_ha)))

highsevarea_ha_20_21 = sum(grove_area_2024$area_ha)

```


```{r grove_clip}

#CBI severity for fires that intersect groves, clipped to groves

cbi_clipped <- st_intersection(cbi_all, groves)
cbi_clipped <- cbi_clipped %>% 
  rename("grov_nm" = "grove_name") %>% 
  select(grov_nm, id, burnsev, fire_yr) 

cbi_clipped$area_ha_grove <- as.numeric(st_area(cbi_clipped))*0.0001 

```
## Known fires in groves since perimeters started

```{r}

all_fires1 <- st_read(here("data/spatial_data/inputs/fire/fire23_1.gdb"), layer = "firep23_1") %>% 
  clean_names() %>%
  st_transform(crs(cbi_all)) %>%  #make consistent crs
  st_cast("MULTIPOLYGON") %>% 
  rownames_to_column() %>% 
  # filter(year>=1914) %>%
  st_intersection(groves)

all_fires <- all_fires1 %>% 
  mutate(fire_name = case_when(!str_detect(fire_name, " ") ~ str_to_title(fire_name), 
    T ~ paste("unknown", rowname, sep = "_")),
         area_ha = as.numeric(st_area(.))*0.0001,
         area_acres = area_ha*2.471) %>% 
  st_drop_geometry() %>% 
select(year, fire_name, grove_name, area_ha) %>%
  bind_rows(grove_area_2024_sum)
  
#tbind_rows()#total area burned
sum(all_fires$area_ha)

all_fires_number_fires = all_fires %>%
  group_by(year, fire_name) %>%
  summarise(area_ha = sum(area_ha)) %>%
  filter(year>=2015)
nrow(all_fires_number_fires)
sum(all_fires_number_fires$area_ha)
summary(all_fires_number_fires$area_ha)


all_fires_groves_annual = all_fires %>%
  group_by(year) %>%
  summarise(area_burned = sum(area_ha), count = length(grove_name))
nrow(all_fires_groves_annual)

summary(all_fires_groves_annual$area_burned)

afga = all_fires_groves_annual %>%
  complete(year = 1910:2024, fill = list(area_burned = 0))

f = ggplot(afga, aes(year,area_burned)) + 
  geom_bar(stat = "identity", position = "dodge", fill = "#88aa11") + 
  theme_bw() +
  xlab("Year") +
  ylab("Area burned (ha)") +
  theme(legend.title=element_blank(),
        legend.position = "none",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), panel.background = element_blank(), 
        # plot.background = element_rect(color = "black", linewidth = 0.5),
        axis.line = element_line(colour = "black"),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(angle = 45, vjust = 1, 
                                   hjust = 1,  size = 12),
        axis.title=element_text(size=14)) +
  scale_y_continuous(labels = comma, limits = c(0,2500), expand = c(0, 0))
f

ggsave(here("outputs/figures_for_manuscript/area_burned_1910_2024.jpg"), 
       width = 11, height = 5)


##get footprint
all_fires_groves_footprint = all_fires1 %>%
  st_union() %>% # unite to a geometry object
  st_sf() %>% # make the geometry a data frame object
  # mutate(keep = T) %>%
   # st_collection_extract("POLYGON") %>%
  st_cast("POLYGON") %>%
    mutate(area_ha = st_area(.)*0.0001)
sum(all_fires_groves_footprint$area_ha)

```



## Fire List

```{r}

all_area <- cbi_all %>% 
  st_drop_geometry() %>% 
  arrange(burnsev) %>% 
  pivot_wider(names_from = burnsev, names_prefix = "all_ha_",values_from = area_ha_total, values_fill = 0) %>% 
  select(!all_ha_255)%>% 
  mutate(all_ha_total = all_ha_1 + all_ha_2 + all_ha_3 + all_ha_4)

grove_area <- cbi_clipped %>% 
  st_drop_geometry() %>% 
  arrange(burnsev) %>% 
  summarise(.by = c(id, burnsev), area_ha_grove = sum(area_ha_grove), grove_ct = length(unique(grov_nm))) %>% 
  pivot_wider(names_from = burnsev, names_prefix = "grove_ha_",values_from = area_ha_grove, values_fill = 0) %>% 
  mutate(grove_ha_total = grove_ha_1 + grove_ha_2 + grove_ha_3 + grove_ha_4)

by_grove <- cbi_clipped %>% 
  st_drop_geometry() %>% 
  summarise(.by= c(id, grov_nm, burnsev), area_ha_grove = sum(area_ha_grove)) %>% 
  pivot_wider(names_from = burnsev, names_prefix = "ha_",values_from = area_ha_grove, values_fill = 0) %>% 
  arrange(id) %>% 
  mutate(ha_total = ha_1 + ha_2 + ha_3 + ha_4) %>% 
  filter(ha_total > 0.01)

grove_count <- by_grove %>% 
  summarize(.by = c(id), grove_count = n())

fire_sev_ha <- by_grove %>% 
  left_join(grove_count) %>% 
  # select(-fire_yr, -assss_t) %>% 
  arrange(id)

write_csv(fire_sev_ha, here("outputs/grove_area_burned_and_count.csv"))


kable(fire_sev_ha, 
      digits = 1,
      caption = "Fire size and severity for fires that burned SEGI groves 1983-2024")


kable(by_grove, 
      digits = 1,
      caption = "Fire severity and size for fires that burned SEGI groves 1983-2024 by grove")

```


## Prelim Figures for Communications

```{r}
#make master dataframe


#need to append info from 2023-2024

recent_fire <- by_grove %>% 
  filter(str_detect(id, "2024")) %>%  #no fires in 2023 somehow, so just need 2024
  mutate(year = "2024", area_acres = ha_total*2.471) %>%
  rename(
    grove_name = grov_nm,
    fire_name = id
  )

# dataframe of years without fire in groves

fire_yrs <- as.integer(unique(all_fires$year))
all_yrs <- 1900:2024

no_fire_yrs <- setdiff(all_yrs, fire_yrs)

no_fire <- tibble(
  year = c(no_fire_yrs) ,
  grove_count = 0,
  fire_count = 0,
  area_acres_total = 0
)



#create complete dataset of fires
all_fires_summary <- all_fires %>% 
  bind_rows(recent_fire) %>%
  summarize(.by = year, 
            grove_count = length(unique(grove_name)),
            fire_count = length(unique(fire_name)),
            area_acres_total = sum(area_acres)) %>% 
  mutate(year = as.numeric(year)) %>% 
  bind_rows(no_fire) %>% 
  arrange(year)

#fire area in groves by severity breakdown by year

severity_summary <- grove_area %>% 
  mutate(year = parse_number(id),
         fire = str_to_title(str_extract(id, "(?<=\\d{4}).+"))) %>% 
  pivot_longer(grove_ha_1:grove_ha_4) %>% 
  summarise(
    .by = c(year, name),
    area_acres = sum(value*2.471)
      ) %>% 
  mutate(
    severity = parse_number(name)
  ) %>% 
  select(-name) %>% 
  pivot_wider(names_from = severity, names_prefix = "area_acres_", values_from = area_acres)


#combine

all_fires_date <- all_fires_summary %>% 
  left_join(severity_summary) %>% # combine severity
  mutate(year = ymd(year, truncated = 2L))
# makes years date format, assigns jan1 as md

```


```{r}
# timeseries of total area burned in groves since 1900
# create xts necessary to use dygraph
all_fires_xts <- all_fires_date %>% 
  select(year, area_acres_total, grove_count, fire_count) %>% 
  mutate(area_acres_total = base::round(area_acres_total, 1),
         grove_count = as.integer(grove_count)) %>% 
  as.xts()
  

#Plot
p <- dygraph(all_fires_xts, main = "Sequoia groves and grove area burned (acres) in wildfires annually 1900 - 2024") %>%
  dyAxis("y", label = "Acres") %>% 
  dyAxis("y2", label = "Count", valueRange = c(0, 30)) %>% 
  dySeries("area_acres_total", label = "Acres burned", axis =('y')) %>% 
  dySeries("grove_count", label = "Groves burned", axis =('y2')) %>% 
  dySeries("fire_count", label = "Number of fires", axis =('y2')) %>% 
  dyOptions(
    stackedGraph = TRUE,
    labelsUTC = TRUE, 
    fillGraph=TRUE, 
    fillAlpha=0.1, 
    drawGrid = FALSE, 
    colors=c( "#713654","#FFD529", "#FEAF3A")) %>%
  dyRangeSelector(fillColor = "burlywood", strokeColor = "") %>%
  dyCrosshair(direction = "vertical") %>%
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesBackgroundAlpha = 0.2, 
              hideOnMouseOut = FALSE)  %>%
  dyLegend(show = "follow")

# save the widget

saveWidget(p, file=here("outputs/acres_year.html"))

```


```{r}
# timeseries of total area burned in groves since 1900
# create xts necessary to use dygraph
severity_xts <- all_fires_date[86:nrow(all_fires_date),] %>%
  select(year, area_acres_total, area_acres_1:area_acres_4) %>% 
  mutate(across(area_acres_total:area_acres_4, base::round,1),
         across(everything(), ~replace_na(.x, 0))) %>% 
  as.xts()
  
  

#Plot
p <- dygraph(severity_xts, main = "Sequoia grove area burned (acres) in wildfires annually 1985 - 2024 by Composite Burn Index (CBI) severity class") %>%
  dyAxis("y", label = "Acres Burned") %>% 
  dySeries("area_acres_total", label = "Total") %>% 
  dySeries("area_acres_1", label = "Undetected change") %>% 
  dySeries("area_acres_2", label = "Low severity") %>% 
  dySeries("area_acres_3", label = "Moderate severity") %>%
  dySeries("area_acres_4", label = "High severity") %>% 
  dyOptions(
    stackedGraph = TRUE,
    labelsUTC = TRUE, 
    fillGraph=TRUE, 
    fillAlpha=0.1, 
    drawGrid = FALSE, 
    colors=c("#FFD529", "#FEAF3A", "#E07D54", "#803A56", "#713654")
    ) %>%
  dyRangeSelector(fillColor = "burlywood", strokeColor = "") %>%
  dyCrosshair(direction = "vertical") %>%
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesBackgroundAlpha = 0.2, 
              hideOnMouseOut = FALSE)  %>%
  dyLegend(show = "follow")

# save the widget

saveWidget(p, file=here("outputs/acres_severity.html"))

```


```{r}

# All fire area in groves since recording began
# modify for easy ggplotting
all_fires_2plot <- all_fires_date %>% 
  select(year, grove_count:area_acres_total) %>% 
  mutate(year = year(year),
         area_acres_total = round(area_acres_total,1),
         grove_count_scale = 300*grove_count,
         across(everything(), ~replace_na(.x, 0)))
  
  
#now make bar chart

ggplot(all_fires_2plot, aes(x = year, y = area_acres_total))+
  geom_col(fill = "goldenrod1")+
  #geom_line(aes(x = year, y = grove_count_scale), color = "peachpuff4")+
  scale_y_continuous(expand = c(0, 0))+ #, sec.axis = sec_axis(trans = ~./ 300, name = "Count of Groves Burned"))+
  labs(
    title = "Sequoia grove area (acres) burned annually by wildfire", subtitle ="1900-2024",
    x = "",
    y = "Total grove area (acres)",
    caption = "(Shive Lab, 2024)" #Total acres of grove area burned annually in wildfires since 1900 (yellow bars) and number of groves burned (brown line)./n
    )+
  #coord_flip()+
  scale_x_reverse()+
  scale_x_continuous(breaks = seq(1900, 2025, by = 10))+
  theme_classic()+
  theme(plot.caption = element_text(hjust = 0, face= "italic"),
        plot.title.position = "plot",
        plot.caption.position =  "plot",
        axis.text.x = element_text(angle = 45, vjust = 1.2, hjust=1))

ggsave(here("outputs/allFires_annualAcres_bar.png"),
       width = 7, height = 6, units = "in", dpi = 600)


```



```{r}

severity_2plot <- all_fires_date %>% 
  select(-fire_count, -grove_count, -area_acres_total) %>% 
  pivot_longer(!year, names_to = "measure") %>% 
  mutate(year = year(year),
         acres = round(value,1),
         across(everything(), ~replace_na(.x, 0)),
         severity = parse_number(measure),
         severity =  base::as.factor(case_when(
             severity == 1 ~ "Undetected change",
             severity == 2 ~ "Low severity",
             severity == 3 ~ "Moderate severity",
             severity == 4 ~ "High severity"
           )),
         severity = factor(severity, levels = c("Undetected change","Low severity","Moderate severity","High severity"))
           ) %>% 
  filter(!year %in% c(1900:1984))




ggplot(severity_2plot, aes(x = year, y = acres, fill = fct_rev(severity)))+
  geom_col()+
  labs(
    title = "Sequoia grove area (acres) burned annually by wildfire by\nComposite Burn Index (CBI) severity class 1985-2024",
    x = "",
    y = "Total grove area (acres)",
    fill = "CBI severity",
    caption = "(Shive Lab, 2024)") +
  #coord_flip()+
   scale_fill_manual(values= c("#233d4d", "#fe7f2d","#a1c181", "#fcca46"))+
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_continuous(breaks = seq(1985, 2025, by = 5), 
                     limits = c(1985, 2025),
                     expand = c(0, 0))+
  theme_classic()+
  theme(plot.caption = element_text(hjust = 0, face= "italic"),
        plot.title.position = "plot",
        plot.caption.position =  "plot",
        axis.text.x = element_text(angle = 45, vjust = 1.3, hjust=1.2),
        legend.position = c(0.2, 0.8))

ggsave(here("outputs/severityFires_annualAcres_stackedbar.png"),
       width = 6, height = 7, units = "in", dpi = 600)

ggplot(severity_2plot, aes(x = year, y = acres, fill = fct_rev(severity)))+
  geom_col()+
  facet_wrap(~severity)+
  labs(
    title = "Sequoia grove area (acres) burned annually by wildfire in each\nComposite Burn Index (CBI) severity class 1985-2024",
    x = "",
    y = "Total grove area (acres)",
    fill = "CBI severity",
    caption = "(Shive Lab, 2024)") +
  #coord_flip()+
  scale_fill_manual(values= c("#233d4d", "#fe7f2d","#a1c181", "#fcca46"))+
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_reverse()+
  scale_x_continuous(breaks = seq(1985, 2025, by = 5), 
                     limits = c(1985, 2025),
                     expand = c(0, 2))+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.caption = element_text(hjust = 0, face= "italic"),
    plot.title.position = "plot",
    plot.caption.position =  "plot",
    axis.text.x = element_text(angle = 45, vjust = 1.3, hjust=1.2))

ggsave(here("outputs/severityFires_annualAcres_facetbar.png"),
       width = 6, height = 6, units = "in", dpi = 600)

```





